version: "3.9"
services:
  composer:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /var/www/html
    command: sh -c "composer update && composer install && php artisan key:generate && php artisan migrate:fresh --seed"
    volumes:
      - ./:/var/www/html
  db: 
    image: mysql:5.7
    restart: always
    env_file:
     - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
  
  php-service-1:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
    - db
    - composer
    volumes:
      - ./:/var/www/html
  
#  php-service-2:
#    build:
#      context: ./.docker
#      dockerfile: Dockerfile
#    ports: 
#    - 8001:9001
#    restart: always
#    depends_on:
#    - db
#    volumes:
#      - ./:/var/www/html

  nginx-1:
    image: nginx
    restart: always
    ports:
     -  "80:80"
    depends_on:
    - php-service-1
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx1:/etc/nginx/conf.d/
  

# nginx-2:
#    image: nginx
#    restart: always
#    depends_on:
#    - php-service-2
#    volumes:
#      - ./:/usr/share/nginx/html
#      - ./.docker/nginx2:/etc/nginx/conf.d/
volumes:
  mysql: