version: "3.9"
services:
  composer1:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /var/www/html
    command: sh -c "composer update && composer install && php artisan key:generate && php artisan migrate"
    volumes:
      - ./laravel1:/var/www/html
  composer2:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /var/www/html
    command: sh -c "composer update && composer install && php artisan key:generate"
    volumes:
      - ./laravel2:/var/www/html
  
  nodejs1:
    image: node:16
    restart: on-failure
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./laravel1:/var/www/html
  nodejs2:
    image: node
    restart: on-failure
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./laravel2:/var/www/html
  db: 
    image: mysql:5.7
    restart: always
    env_file:
     - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
  
  php-service-1:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
    - db
    - composer1
    volumes:
      - ./laravel1:/var/www/html
  
  php-service-2:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
    - db
    - composer2
    volumes:
      - ./laravel2:/var/www/html

  nginx-1:
    image: nginx
    restart: always
    ports:
     -  "80:80"
    depends_on:
    - php-service-1
    volumes:
      - ./laravel1:/var/www/html
      - ./.docker/nginx1:/etc/nginx/conf.d/

  
  nginx-2:
    image: nginx
    restart: always
    ports:
      -  "81:80"
    depends_on:
    - php-service-2
    volumes:
      - ./laravel2:/var/www/html
      - ./.docker/nginx2:/etc/nginx/conf.d/

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      -  "8025:8025"
      -  "1025:1025"
volumes:
  mysql: